# Generated by Django 4.2 on 2023-05-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
