# Generated by Django 4.2 on 2023-04-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reviews_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='points',
        ),
    ]
