# Generated by Django 4.2 on 2023-05-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_birth_date_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
